[project]
name = 'institutional-sbtc-treasury'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.anchorage-interface]
path = 'contracts/anchorage-interface.clar'
clarity_version = 3
epoch = 3.1

[contracts.bitgo-interface]
path = 'contracts/bitgo-interface.clar'
clarity_version = 3
epoch = 3.1

[contracts.fireblocks-interface]
path = 'contracts/fireblocks-interface.clar'
clarity_version = 3
epoch = 3.1

[contracts.treasury-manager]
path = 'contracts/treasury-manager.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
